# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='javascript',
            field=models.TextField(default='', verbose_name='body'),
            preserve_default=False,
        ),
    ]
