# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_javascript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='javascript',
            field=models.TextField(verbose_name='js'),
        ),
    ]
