# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170527_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='is-demo'),
        ),
    ]
